# Generated by Django 5.1.7 on 2025-04-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_owner',
            new_name='is_landlord',
        ),
    ]
