version: '3.9'

services:
  renthub-web:
    build: .  # Указываем, что нужно строить из текущей директории (где находится Dockerfile для Django)
    container_name: renthub-web
    restart: always
    depends_on:
      - mysql
    expose:
      - "8000"
    volumes:
      - static_volume:/RentHub/staticfiles
      - media_volume:/RentHub/media
    env_file:
      - .env  # Указываем, что нужно использовать файл .env
    command: gunicorn RentHub.wsgi:application --bind 0.0.0.0:8000

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    env_file:
      - .env  # Используем тот же .env файл для настроек базы данных
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest  # Используем стандартный образ Nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Подключаем вашу конфигурацию Nginx
      - static_volume:/RentHub/staticfiles  # Монтируем статические файлы
      - media_volume:/RentHub/media  # Монтируем медиа-файлы
    depends_on:
      - renthub-web

volumes:
  mysql_data:
  static_volume:
  media_volume:
