# Generated by Django 5.1.7 on 2025-04-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='review',
        ),
    ]
