# Generated by Django 5.1.7 on 2025-04-01 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
        ('listings', '0003_remove_listing_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.review'),
        ),
    ]
