# Generated by Django 5.1.7 on 2025-04-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='owner_email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
