# Generated by Django 5.1.7 on 2025-04-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='listings/images/'),
        ),
    ]
