# Generated by Django 5.1.7 on 2025-04-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_review_alter_listing_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner',
            new_name='landlord',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='owner_email',
            new_name='landlord_email',
        ),
    ]
