# Generated by Django 5.1.7 on 2025-04-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_review_listing_alter_listing_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='review',
        ),
        migrations.AddField(
            model_name='listing',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
