# Generated by Django 5.1.7 on 2025-04-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_listing_review_listing_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
