# Generated by Django 5.1.7 on 2025-04-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_review_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='listing',
        ),
    ]
