# Generated by Django 5.1.7 on 2025-04-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_review_booking_remove_review_user'),
        ('listings', '0006_review_alter_listing_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
