# Generated by Django 5.1.7 on 2025-04-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='landlord_email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
